# Site
repository: magitz/modern-resume-alberta-jane
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alberta Jane 
title: 
email: ajane@ufl.edu
website: https://magitz.github.io/modern-resume-alberta-jane/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: UFCareerCenter
github_username:  magitz
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bachelor of Science in Industrial and Systems Engineering   May 2020
        quote: > 
          University of Florida, GPA GPA: 3.83/4.0 
        description: | # this will include new lines to allow paragraphs
          Study Abroad: Florence, Italy

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Walk Disney World, Lake Buena Vista, FL
        sub_title: Industrial Engineering Professional Intern
        caption: Aug 2019- Dec 2019
        description: | # this will include new lines to allow paragraphs
          *	Conducted data analysis and statistical modeling to provide planning, capacity utilization support, and efficiency solutions for the Resort and Transportation Operations
          *	Led a business analysis project that identified process improvements to annually save $2.8 Million in transportation operational costs when implemented
          *	Designed and Programmed 3 apps in Filemaker Pro to support operations during the opening of the Disney Skyliner and collected data through field studies to provide efficiency recommendations

        title: Supply Chain Co-op, GE Appliances, a Haier Company, Louisville, KY
        sub_title: Customer Fulfillment
        caption: May 2019-Aug 2019
        description: | # this will include new lines to allow paragraphs
          *	Monitored inventory levels to ensure multi-family accounts received their orders on time. When needed worked with Warehousing and Transportation Teams to implement solutions to prevent backorders
          *	Analyzed allocation issues within the 9 distribution centers and recommend alternative allocation strategies for specific situations to management as needed
          *	Created tools using VBA to automatically generate reports detailing key fulfillment metrics and shared the metrics weekly with my accounts   

        title: Supply Chain Co-op, GE Appliances, a Haier Company, Louisville, KY
        sub_title: Materials Planner 
        caption: Aug 2018-Dec 2018
        description:
          *	Participated in a two-day Kaizen event to implement preventative maintenance for Braider Machines
          *	Wrote a Scrap Macro using VBA which sorted through 100,000 lines of raw data, to find the top 15 reasons for the largest scrap reports
          *	Implemented a color sensor to increase detection capability of splices and defects in wires. Used SolidWorks to mount the color sensor to the machine

  - title: Leadership involvement # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UF Club Swim and Dive Team
        caption: Aug 2015 - Present
        description: | # this will include new lines to allow paragraphs
          * Attended swim practice four times per week, weekend travel to compete against other university clubs, and helped the team place 2nd at the National Championships for 2015 and 2016 

        title: UF Institute of Industrial and System Engineering
        caption: Jan 2016 - Present

        title: ExercIISE Committee
        caption: Aug 2017 - May 2018
        description: | # this will include new lines to allow paragraphs
          * Utilized social media and Google Apps to create event pages to increase participation of members
          * Responsible for arranging and managing functions that promote athletics, such as 2 intramural teams with 20 members 
        and sporting events for our entire club

- title: Honors # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Florida Deans List 
        caption: Spring 2016 - Present

- title: Computer Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        description: Proficient in VBA, Microsoft Office, Oracle, VB.NET, RStudio, Arena, SolidWorks and Filemaker Pro 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
